openapi: "3.0.1"
info:
  title: "API Documentation"
  version: "1.0"
paths:
  /operators/list:
    post:
      summary: "operatorsListPost"
      description: "operatorsListPost"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                page:
                  type: "integer"
                  description: ""
                size:
                  type: "integer"
                  description: ""
                categories:
                  type: "array"
                  description: ""
                  items:
                    type: "integer"
                  default: "new ArrayList<>()"
                operatorName:
                  type: "string"
                  description: ""
                labelName:
                  type: "string"
                  description: ""
                isStar:
                  type: "boolean"
                  description: ""
              description: ""
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  page:
                    type: "integer"
                    description: ""
                    format: "int64"
                  size:
                    type: "integer"
                    description: ""
                    format: "int64"
                  totalElements:
                    type: "integer"
                    description: ""
                    format: "int64"
                  totalPages:
                    type: "integer"
                    description: ""
                    format: "int64"
                  content:
                    type: "array"
                    description: ""
                    items:
                      type: "object"
                      properties:
                        id:
                          type: "string"
                          description: ""
                        name:
                          type: "string"
                          description: ""
                        description:
                          type: "string"
                          description: ""
                        version:
                          type: "string"
                          description: ""
                        inputs:
                          type: "string"
                          description: ""
                        outputs:
                          type: "string"
                          description: ""
                        categories:
                          type: "array"
                          description: ""
                          items:
                            type: "string"
                        runtime:
                          type: "string"
                          description: ""
                        settings:
                          type: "string"
                          description: ""
                        fileName:
                          type: "string"
                          description: ""
                        isStar:
                          type: "boolean"
                          description: ""
                        createdAt:
                          type: "string"
                          description: ""
                        updatedAt:
                          type: "string"
                          description: ""
                      description: "OperatorDto"
  /operators/{id}:
    get:
      summary: "operatorsIdGet"
      description: "operatorsIdGet"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: ""
                  name:
                    type: "string"
                    description: ""
                  description:
                    type: "string"
                    description: ""
                  version:
                    type: "string"
                    description: ""
                  inputs:
                    type: "string"
                    description: ""
                  outputs:
                    type: "string"
                    description: ""
                  categories:
                    type: "array"
                    description: ""
                    items:
                      type: "string"
                  runtime:
                    type: "string"
                    description: ""
                  settings:
                    type: "string"
                    description: ""
                  fileName:
                    type: "string"
                    description: ""
                  isStar:
                    type: "boolean"
                    description: ""
                  createdAt:
                    type: "string"
                    description: ""
                  updatedAt:
                    type: "string"
                    description: ""
    put:
      summary: "operatorsIdPut"
      description: "operatorsIdPut"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: "string"
                  description: ""
                name:
                  type: "string"
                  description: ""
                description:
                  type: "string"
                  description: ""
                version:
                  type: "string"
                  description: ""
                inputs:
                  type: "string"
                  description: ""
                outputs:
                  type: "string"
                  description: ""
                categories:
                  type: "array"
                  description: ""
                  items:
                    type: "string"
                runtime:
                  type: "string"
                  description: ""
                settings:
                  type: "string"
                  description: ""
                fileName:
                  type: "string"
                  description: ""
                isStar:
                  type: "boolean"
                  description: ""
                createdAt:
                  type: "string"
                  description: ""
                updatedAt:
                  type: "string"
                  description: ""
              description: ""
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: ""
                  name:
                    type: "string"
                    description: ""
                  description:
                    type: "string"
                    description: ""
                  version:
                    type: "string"
                    description: ""
                  inputs:
                    type: "string"
                    description: ""
                  outputs:
                    type: "string"
                    description: ""
                  categories:
                    type: "array"
                    description: ""
                    items:
                      type: "string"
                  runtime:
                    type: "string"
                    description: ""
                  settings:
                    type: "string"
                    description: ""
                  fileName:
                    type: "string"
                    description: ""
                  isStar:
                    type: "boolean"
                    description: ""
                  createdAt:
                    type: "string"
                    description: ""
                  updatedAt:
                    type: "string"
                    description: ""
  /operators/create:
    post:
      summary: "operatorsCreatePost"
      description: "operatorsCreatePost"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: "string"
                  description: ""
                name:
                  type: "string"
                  description: ""
                description:
                  type: "string"
                  description: ""
                version:
                  type: "string"
                  description: ""
                inputs:
                  type: "string"
                  description: ""
                outputs:
                  type: "string"
                  description: ""
                categories:
                  type: "array"
                  description: ""
                  items:
                    type: "string"
                runtime:
                  type: "string"
                  description: ""
                settings:
                  type: "string"
                  description: ""
                fileName:
                  type: "string"
                  description: ""
                isStar:
                  type: "boolean"
                  description: ""
                createdAt:
                  type: "string"
                  description: ""
                updatedAt:
                  type: "string"
                  description: ""
              description: ""
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: ""
                  name:
                    type: "string"
                    description: ""
                  description:
                    type: "string"
                    description: ""
                  version:
                    type: "string"
                    description: ""
                  inputs:
                    type: "string"
                    description: ""
                  outputs:
                    type: "string"
                    description: ""
                  categories:
                    type: "array"
                    description: ""
                    items:
                      type: "string"
                  runtime:
                    type: "string"
                    description: ""
                  settings:
                    type: "string"
                    description: ""
                  fileName:
                    type: "string"
                    description: ""
                  isStar:
                    type: "boolean"
                    description: ""
                  createdAt:
                    type: "string"
                    description: ""
                  updatedAt:
                    type: "string"
                    description: ""
  /operators/upload:
    post:
      summary: "operatorsUploadPost"
      description: "operatorsUploadPost"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                reqId:
                  type: "string"
                  description: "预上传返回的id，用来确认同一个任务"
                fileNo:
                  type: "integer"
                  description: "文件编号，用于标识批量上传中的第几个文件"
                fileName:
                  type: "string"
                  description: "文件名称"
                totalChunkNum:
                  type: "integer"
                  description: "文件总分块数量"
                chunkNo:
                  type: "integer"
                  description: "当前分块编号，从1开始"
                file:
                  type: "string"
                  description: "上传的文件分块内容"
                checkSumHex:
                  type: "string"
                  description: "文件分块的校验和（十六进制字符串），用于验证文件完整性"
              description: ""
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  id:
                    type: "string"
                    description: ""
                  name:
                    type: "string"
                    description: ""
                  description:
                    type: "string"
                    description: ""
                  version:
                    type: "string"
                    description: ""
                  inputs:
                    type: "string"
                    description: ""
                  outputs:
                    type: "string"
                    description: ""
                  categories:
                    type: "array"
                    description: ""
                    items:
                      type: "string"
                  runtime:
                    type: "string"
                    description: ""
                  settings:
                    type: "string"
                    description: ""
                  fileName:
                    type: "string"
                    description: ""
                  isStar:
                    type: "boolean"
                    description: ""
                  createdAt:
                    type: "string"
                    description: ""
                  updatedAt:
                    type: "string"
                    description: ""
  /operators/upload/pre-upload:
    post:
      summary: "preUpload"
      description: "preUpload"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: "string"
  /operators/upload/chunk:
    post:
      summary: "chunkUpload"
      description: "chunkUpload"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                reqId:
                  type: "string"
                  description: "预上传返回的id，用来确认同一个任务"
                fileNo:
                  type: "integer"
                  description: "文件编号，用于标识批量上传中的第几个文件"
                fileName:
                  type: "string"
                  description: "文件名称"
                totalChunkNum:
                  type: "integer"
                  description: "文件总分块数量"
                chunkNo:
                  type: "integer"
                  description: "当前分块编号，从1开始"
                file:
                  type: "string"
                  description: "上传的文件分块内容"
                checkSumHex:
                  type: "string"
                  description: "文件分块的校验和（十六进制字符串），用于验证文件完整性"
              description: ""
      responses:
        "200":
          description: "No Content"
components:
  schemas:
    OperatorDto:
      type: "object"
      properties:
        id:
          type: "string"
          description: ""
        name:
          type: "string"
          description: ""
        description:
          type: "string"
          description: ""
        version:
          type: "string"
          description: ""
        inputs:
          type: "string"
          description: ""
        outputs:
          type: "string"
          description: ""
        categories:
          type: "array"
          description: ""
          items:
            type: "string"
        runtime:
          type: "string"
          description: ""
        settings:
          type: "string"
          description: ""
        fileName:
          type: "string"
          description: ""
        isStar:
          type: "boolean"
          description: ""
        createdAt:
          type: "string"
          description: ""
        updatedAt:
          type: "string"
          description: ""
      description: "OperatorDto"
